#!/bin/bash
# Date : (2015-12-09)
# Distribution used to test : Ubuntu 14.04 64 bit
# Author : Lukonin Kirill
# Licence : GPLv3
# PlayOnLinux: 4.2.9
 
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
PREFIX="Nextion"
WINEVERSION="1.9.16-staging"
TITLE="Nextion Editor 0.37"
EDITOR="ITEAD Studio"
ZIP_URL="http://dl.itead.cc/Nextion/nextion-setup-v037.zip"
AUTHOR="Lukonin Kirill"
 
#Initialization
POL_SetupWindow_Init
POL_Debug_Init
 
#Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$AUTHOR" "$PREFIX"
  
POL_SetupWindow_message "$(eval_gettext 'IMPORTANT: This program may work not well on Linux. Be careful. It is also need to run a sudo command once. Please follow the instructions')" "$TITLE"
 
POL_Call POL_Function_RootCommand "echo 0|sudo tee /proc/sys/kernel/yama/ptrace_scope; exit"
 
# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WINEVERSION"
Set_OS "win7"
 
# Component_inslallation
Set_OS "win7"
POL_SetupWindow_message "$(eval_gettext 'Please install .NET framework. Please wait.')" "$TITLE"
POL_Call POL_Install_dotnet45
POL_SetupWindow_message "$(eval_gettext 'PLease install Internet Explorer 8. Click NEXT and ACCEPT during the installation process.')" "$TITLE"
Set_OS "winxp"
POL_Call POL_Install_ie8


#Saftware installation
POL_System_TmpCreate "$PREFIX"
cd "$POL_System_TmpDir"
POL_Download $"ZIP_URL"
unzip nextion-setup-v*.zip
   
# Create Shortcuts
POL_Shortcut "Nextion Editor.exe" "$TITLE"
       
POL_SetupWindow_Close
exit 0
 
